# Generated by Django 3.1.1 on 2021-06-13 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='excel',
            name='pdf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.pdf'),
        ),
    ]
